linters:
  enable-all: true
  disable:
    # Magic number checker. Most of the time, the magic numbers in the are
    # necessary.
    - mnd
    # Variable name lengths. I find that most of the variables with short names
    # require short names, or it doesn't make sense to give them long ones.
    - varnamelen
    # This linter checks to make sure that nothing is writing output. For what
    # these programs are doing, 99% of the time, they need to write to STDOUT.
    - forbidigo

linters-settings:
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/charmbracelet/bubbletea
          - github.com/charmbracelet/lipgloss
          - github.com/charmbracelet/huh
          - github.com/Kaamkiya/gg
        deny:
          - pkg: "math/rand$"
            desc: "Use math/rand/v2, or crypto/rand instead."
          - pkg: "reflect"
            desc: "You shouldn't need dynamic types. Make an issue if you do."
