#!/bin/sh

echo "Building for linux amd64..."
GOOS=linux GOARCH=amd64 go build -o gg-linux-amd64 ./cmd/gg/
echo "Building for linux arm64..."
GOOS=linux GOARCH=arm64 go build -o gg-linux-arm64 ./cmd/gg/
echo "Building for windows amd64..."
GOOS=windows GOARCH=amd64 go build -o gg-windows-amd64.exe ./cmd/gg/
echo "Building for windows arm64..."
GOOS=windows GOARCH=arm64 go build -o gg-windows-arm64.exe ./cmd/gg/
echo "Building for darwin amd64..."
GOOS=darwin GOARCH=amd64 go build -o gg-darwin-amd64 ./cmd/gg/
echo "Building for darwin arm64..."
GOOS=darwin GOARCH=arm64 go build -o gg-darwin-arm64 ./cmd/gg/
